---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plm)
library(tidyverse)
library(estimatr)
library(ggalt)
library(wooldridge)
library(GGally)
library(sandwich)
library(lmtest)
library(mosaic)
library(broom)
library(car)
library(patchwork)
cars <- read.csv("cars.csv", sep=";")
test <- read_csv("test.csv")
```

```{r}
test %>% select(var2) %>% inspect()
```

```{r}
inspect(cars)
cars %>% select(MPG, Cylinders, Displacement, Horsepower, Weight, Acceleration) %>% ggpairs()
```

```{r}
e <- cars %>% filter(Origin == "Europe") %>% ggplot(aes(x = Displacement, y = MPG, color = as.factor(Cylinders))) + geom_point()
u <- cars %>% filter(Origin == "US") %>% ggplot(aes(x = Displacement, y = MPG, color = as.factor(Cylinders))) + geom_point()
cars %>% filter(Origin == "Europe" | Origin == "US") %>% filter(MPG > 0) %>% ggplot(aes(x = Displacement, y = MPG, color = as.factor(Origin))) + geom_point()
e + u
```

```{r}
mpg_model <- lm(MPG~Displacement + Cylinders + Acceleration, data = cars)
summary(mpg_model)
coeftest(mpg_model, vcov = vcovHC, type = "HC1")
cor(Displacement~Horsepower, data = cars)
cor(Displacement~Cylinders, data = cars)
```

```{r}
cars %>% filter(Origin == "US") %>% ggplot(aes(x = Model, y = MPG)) + geom_smooth(method = "lm") + geom_point()
```
